Enviar submissão leoralph
zanfranceschi/rinha-de-backend-2024-q1 pull request #47
Opened 2024-02-08 15:16 UTC by leoralph

2024-02-08 22:28 UTC, zanfranceschi requested changes
Você precisa enviar seu docker-compose já apontando pra uma imagem buildada e publicamente acessível, ok? Builda e faz o push dela pro docker hub ou algo assim.

2024-02-08 23:40 UTC, leoralph commented
@zanfranceschi corrigido

2024-02-08 23:43 UTC, leoralph commented
> Você precisa enviar seu docker-compose já apontando pra uma imagem buildada e publicamente acessível, ok? Builda e faz o push dela pro docker hub ou algo assim.

@zanfranceschi corrigido

2024-02-09 01:01 UTC, zanfranceschi approved these changes
boa!

2024-02-09 01:01 UTC, merged